# Generated by Django 3.2.5 on 2021-08-07 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegralActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MajorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('integralActitivty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start1.integralactivity')),
            ],
        ),
        migrations.AddField(
            model_name='integralactivity',
            name='majorActivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start1.majoractivity'),
        ),
        migrations.CreateModel(
            name='InherentRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('riskCatagory', models.CharField(choices=[('1', 'Financial'), ('2', 'Reputational'), ('3', 'Marketing'), ('4', 'Legal')], max_length=30)),
                ('procedureManual', models.CharField(choices=[('1', 'Available'), ('2', 'Not Available')], max_length=30)),
                ('makerChecker', models.CharField(choices=[('1', 'Available'), ('2', 'Not Available')], max_length=30)),
                ('dualControl', models.CharField(choices=[('1', 'Available'), ('2', 'Not Available')], max_length=30)),
                ('frequencyofExposure', models.CharField(choices=[('1', 'Daily'), ('2', 'Weekly'), ('3', 'Monthly'), ('4', 'Quarterly'), ('5', 'Semi Anually'), ('6', 'Anually')], max_length=30)),
                ('riskCondition', models.CharField(choices=[('1', 'Reversible'), ('2', 'Irreversible')], max_length=30)),
                ('consequence', models.CharField(choices=[('1', 'Insignificant'), ('2', 'Moderate'), ('3', 'Major'), ('4', 'Catastrophic')], max_length=30)),
                ('riskMitigation', models.CharField(choices=[('1', 'Tolerate'), ('2', 'Treat'), ('3', 'Transfer'), ('4', 'Terminate')], max_length=30)),
                ('owner', models.CharField(max_length=300)),
                ('targetCompletion', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=300)),
                ('unrectifiedAuditFindings', models.CharField(choices=[('1', 'Found'), ('2', 'Not found')], max_length=30)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start1.objective')),
            ],
        ),
    ]
