# Generated by Django 3.2.7 on 2021-10-12 08:51

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('start1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Office', 'Office'), ('Department', 'Department'), ('Branch', 'Branch')], max_length=30)),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='integralactivity',
            old_name='majorActivity',
            new_name='major_Activity',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='integralActitivty',
            new_name='integral_Actitivty',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='dualControl',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='frequencyofExposure',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='makerChecker',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='procedureManual',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='riskCatagory',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='riskCondition',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='riskMitigation',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='targetCompletion',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='unrectifiedAuditFindings',
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='dual_Control',
            field=models.CharField(blank=True, choices=[('AV', 'Available'), ('NA', 'Not Available')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='frequency_of_Exposure',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi Anually', 'Semi Anually'), ('Anually', 'Anually')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='it_Sytem',
            field=models.CharField(blank=True, choices=[('AV', 'Available'), ('NA', 'Not Available')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='maker_Checker',
            field=models.CharField(blank=True, choices=[('AV', 'Available'), ('NA', 'Not Available')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='monetary_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='privilage',
            field=models.CharField(blank=True, choices=[('AV', 'Available'), ('NA', 'Not Available')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='procedure_Manual',
            field=models.CharField(blank=True, choices=[('AV', 'Available'), ('NA', 'Not Available')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='risk_Catagory',
            field=models.CharField(blank=True, choices=[('Financial', 'Financial'), ('Reputational', 'Reputational'), ('Marketing', 'Marketing'), ('Legal', 'Legal')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='risk_Condition',
            field=models.CharField(blank=True, choices=[('Reversible', 'Reversible'), ('Irreversible', 'Irreversible')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='risk_Level',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('Significant', 'Significant'), ('High', 'High'), ('Extreme', 'Extreme')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='risk_Mitigation',
            field=models.CharField(blank=True, choices=[('Tolerate', 'Tolerate'), ('Treat', 'Treat'), ('Transfer', 'Transfer'), ('Terminate', 'Terminate')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='target_Completion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='unrectified_Audit_Findings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='consequence',
            field=models.CharField(blank=True, choices=[('Insignificant', 'Insignificant'), ('Moderate', 'Moderate'), ('Major', 'Major'), ('Catastrophic', 'Catastrophic')], max_length=30),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='objective',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='start1.objective'),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='owner',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='status',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
                ('working_Place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start1.branch')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='majoractivity',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='start1.branch'),
            preserve_default=False,
        ),
    ]
