# Generated by Django 3.2.5 on 2021-08-10 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inherentrisk',
            name='consequence',
            field=models.CharField(blank=True, choices=[('Insignificant', 'Insignificant'), ('Moderate', 'Moderate'), ('Major', 'Major'), ('Catastrophic', 'Catastrophic')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='dualControl',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('NA', 'NA')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='frequencyofExposure',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi Anually', 'Semi Anually'), ('Anually', 'Anually')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='makerChecker',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('NA', 'NA')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='start1.objective'),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='owner',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='procedureManual',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('NA', 'NA')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='riskCatagory',
            field=models.CharField(blank=True, choices=[('Financial', 'Financial'), ('Reputational', 'Reputational'), ('Marketing', 'Marketing'), ('Legal', 'Legal')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='riskCondition',
            field=models.CharField(blank=True, choices=[('Reversible', 'Reversible'), ('Irreversible', 'Irreversible')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='riskMitigation',
            field=models.CharField(blank=True, choices=[('Tolerate', 'Tolerate'), ('Treat', 'Treat'), ('Transfer', 'Transfer'), ('Terminate', 'Terminate')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='status',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='targetCompletion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='unrectifiedAuditFindings',
            field=models.CharField(blank=True, choices=[('Found', 'Found'), ('Not Found', 'Not found')], max_length=30, null=True),
        ),
    ]
