# Generated by Django 3.2.5 on 2021-08-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start1', '0002_auto_20210810_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Office', 'Office'), ('Department', 'Department'), ('Branch', 'Branch')], max_length=30)),
                ('name', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='majoractivity',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='start1.branch'),
            preserve_default=False,
        ),
    ]
