# Generated by Django 3.2.7 on 2021-10-12 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start1', '0003_alter_customuser_working_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='majoractivity',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='majoractivity',
            name='branch',
            field=models.CharField(max_length=100),
        ),
    ]
