# Generated by Django 3.2.7 on 2021-10-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('start1', '0003_auto_20210812_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integralactivity',
            old_name='majorActivity',
            new_name='major_Activity',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='integralActitivty',
            new_name='integral_Actitivty',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='dualControl',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='frequencyofExposure',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='makerChecker',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='procedureManual',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='riskCatagory',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='riskCondition',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='riskMitigation',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='targetCompletion',
        ),
        migrations.RemoveField(
            model_name='inherentrisk',
            name='unrectifiedAuditFindings',
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='dual_Control',
            field=models.CharField(blank=True, choices=[('AV', 'Available'), ('NA', 'Not Available')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='frequency_of_Exposure',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Semi Anually', 'Semi Anually'), ('Anually', 'Anually')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='it_Sytem',
            field=models.CharField(blank=True, choices=[('AV', 'Available'), ('NA', 'Not Available')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='maker_Checker',
            field=models.CharField(blank=True, choices=[('AV', 'Available'), ('NA', 'Not Available')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='monetary_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='privilage',
            field=models.CharField(blank=True, choices=[('AV', 'Available'), ('NA', 'Not Available')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='procedure_Manual',
            field=models.CharField(blank=True, choices=[('AV', 'Available'), ('NA', 'Not Available')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='risk_Catagory',
            field=models.CharField(blank=True, choices=[('Financial', 'Financial'), ('Reputational', 'Reputational'), ('Marketing', 'Marketing'), ('Legal', 'Legal')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='risk_Condition',
            field=models.CharField(blank=True, choices=[('Reversible', 'Reversible'), ('Irreversible', 'Irreversible')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='risk_Mitigation',
            field=models.CharField(blank=True, choices=[('Tolerate', 'Tolerate'), ('Treat', 'Treat'), ('Transfer', 'Transfer'), ('Terminate', 'Terminate')], max_length=30),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='target_Completion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='unrectified_Audit_Findings',
            field=models.CharField(blank=True, choices=[('Found', 'Found'), ('Not Found', 'Not found')], max_length=30),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='consequence',
            field=models.CharField(blank=True, choices=[('Insignificant', 'Insignificant'), ('Moderate', 'Moderate'), ('Major', 'Major'), ('Catastrophic', 'Catastrophic')], max_length=30),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='objective',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='start1.objective'),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='owner',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='inherentrisk',
            name='status',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
