# Generated by Django 3.2.7 on 2021-10-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start1', '0004_auto_20211012_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majoractivity',
            name='branch',
        ),
    ]
