# Generated by Django 3.2.7 on 2021-10-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start1', '0006_auto_20211019_1148'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='WorkUnit',
        ),
    ]
