# Generated by Django 3.2.7 on 2021-10-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start1', '0007_rename_branch_workunit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objective',
            old_name='integral_Actitivty',
            new_name='integral_Activity',
        ),
    ]
