# Generated by Django 3.2.7 on 2021-10-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start1', '0008_rename_integral_actitivty_objective_integral_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inherentrisk',
            old_name='it_Sytem',
            new_name='it_System',
        ),
    ]
