# Generated by Django 3.2.7 on 2021-10-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start1', '0009_rename_it_sytem_inherentrisk_it_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='inherentrisk',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
