# Generated by Django 3.2.7 on 2021-10-27 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start1', '0011_auto_20211026_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_IadUSer',
            new_name='is_Iad_USer',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='is_RmcdUser',
            new_name='is_Rmcd_User',
        ),
    ]
