# Generated by Django 3.2.7 on 2021-11-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start1', '0013_auto_20211105_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inherentrisk',
            name='status',
        ),
        migrations.AddField(
            model_name='inherentrisk',
            name='management_Plan',
            field=models.TextField(blank=True),
        ),
    ]
